// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFFtwe-RyDOBsH-uK4c5RR9yD23ZMMQzM',
    appId: '1:123394977959:web:e0e4d8006834720ed0ab82',
    messagingSenderId: '123394977959',
    projectId: 'keepscore2dev',
    authDomain: 'keepscore2dev.firebaseapp.com',
    databaseURL: 'https://keepscore2dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'keepscore2dev.appspot.com',
    measurementId: 'G-K917VYV2J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAql1AP3mPwQrxbQm1i5CLWw-_uXhRiJQA',
    appId: '1:123394977959:android:db2a1e709edce9f5d0ab82',
    messagingSenderId: '123394977959',
    projectId: 'keepscore2dev',
    databaseURL: 'https://keepscore2dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'keepscore2dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWs-VMlXiAHUGMO6DZIliBYJPiPyh5E8k',
    appId: '1:123394977959:ios:8b5f08cd1a41c269d0ab82',
    messagingSenderId: '123394977959',
    projectId: 'keepscore2dev',
    databaseURL: 'https://keepscore2dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'keepscore2dev.firebasestorage.app',
    iosBundleId: 'com.example.keepscore2Flutter',
  );

}